[features]
seeds = false
[programs.localnet]
rehacek_ssos = "HkTuJtyhu7yFYGkZ5cyZrvYS6By6rPxRo4ydfnbYPQ7T"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/ondrejrehacek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
